//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PakistaniTwitter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_PakistaniTwitter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_PakistaniTwitter()
        {
            this.Followers_PakistaniTwitter = new HashSet<Followers_PakistaniTwitter>();
            this.Followers_PakistaniTwitter1 = new HashSet<Followers_PakistaniTwitter>();
            this.Tweets_PakistaniTwitter = new HashSet<Tweets_PakistaniTwitter>();
        }
    
        public string UserId { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public System.DateTime Joined { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Followers_PakistaniTwitter> Followers_PakistaniTwitter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Followers_PakistaniTwitter> Followers_PakistaniTwitter1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tweets_PakistaniTwitter> Tweets_PakistaniTwitter { get; set; }
    }
}
